version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./public:/public
    links:
      - mysql
  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./public:/public
  mysql:
    image: mariadb:latest
    env_file:
      - .env
    environment:
      MYSQL_SERVERNAME: '${DB_HOST}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:${DB_PORT:-3306}'
volumes:
  mysqldata: { }